# Exported from Render on 2025-03-15T22:01:10Z
services:
- type: web
  name: bitget-notification-bot
  runtime: python
  repo: https://github.com/Fruchtii/bitget-notification-bot
  plan: free
  envVars:
  - key: TRADER_ID
    sync: false
  - key: TELEGRAM_CHAT_ID
    sync: false
  - key: TELEGRAM_BOT_TOKEN
    sync: false
  - key: BITGET_PASSPHRASE
    sync: false
  - key: BITGET_SECRET_KEY
    sync: false
  - key: BITGET_API_KEY
    sync: false
  region: frankfurt
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn bot:app
version: "1"
